package quiz.exception


/**
 * Write a code where end one coroutine with an exception and print it, and that exception
 * will be thrown by await(). End another coroutine that will print “Hello World”
 * Use the try and catch block for handling exceptions.
 *
 * Output:
 * kotlinx.coroutines.app.MyException
 * Hello World
 */
suspend fun main() {

}

